# 基础镜像
FROM docker.io/williamyeh/java8
# 对应pom.xml文件中的dockerfile-maven-plugin插件buildArgs配置项JAR_FILE的值
ARG JAR_FILE
# 复制打包完成后的jar文件到镜像下得/opt目录下
COPY ${JAR_FILE} /opt/app.jar
# 挂载点，开启了log和文件存放的两个挂载点
VOLUME ["/logs","/file/img"]
# 启动容器时执行
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/opt/app.jar"]
# 使用端口8180 端口可自行配置
EXPOSE 8180