spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12354
  mvc:
    static-path-pattern: /file/**
  resources:
    static-locations: file:Users/curry/Documents/tms/temp/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.kj0901.tms.base.entity
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: debug

###--以下是自定义属性
files:
  upPath: Users/curry/Documents/tms/temp/
  showUrl: http://127.0.0.1:8082/file/


